<?php

/**
 * @file
 * Contains push_notifications.module functionality.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * OS device types IDs.
 */
const PUSH_NOTIFICATIONS_TYPE_ID_IOS = 0;
const PUSH_NOTIFICATIONS_TYPE_ID_ANDROID = 1;

/**
 * APNS notification server port.
 */
const PUSH_NOTIFICATIONS_APNS_PORT = 2195;

/**
 * APNS feedback host.
 */
const PUSH_NOTIFICATIONS_APNS_FEEDBACK_HOST = 'feedback.push.apple.com';

/**
 * APNS feedback port.
 */
const PUSH_NOTIFICATIONS_APNS_FEEDBACK_PORT = 2196;

/**
 * APNS size limit for individual payload, in bytes.
 */
const PUSH_NOTIFICATIONS_APNS_PAYLOAD_SIZE_LIMIT = 2048;

/**
 * GCM notification post URL.
 */
const PUSH_NOTIFICATIONS_GCM_SERVER_POST_URL = 'https://android.googleapis.com/gcm/send';


/**
 * Implements hook_help().
 */
function push_notifications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the push_notifications module.
    case 'help.page.push_notifications':
      $doc_url = Url::fromUri('https://www.drupal.org/node/2718063', array(
        'attributes' => array(
          'target' => '_blank',
        ),
      ));
      $doc_link = Link::fromTextAndUrl('Book admin', $doc_url);
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Push notification functionality for iPhone and Android.') . '</p>';
      $output .= '<p>' . t('The full documentation is available online: @doc_link.', array('@doc_link' => $doc_link->toString())) . '</p>';
      return $output;
  }
}

/**
 * Generate and set the random file ending for APNS certificates.
 */
function push_notifications_set_random_certificate_string() {
  // Generate a random 10-digit string.
  $random_string = substr(md5(microtime()), 0, 10);

  // Write random string to variables.
  $config = \Drupal::service('config.factory')->getEditable('push_notifications.apns');
  $config->set('certificate_random', 'push_notifications_apns_certificate_random' . '-' . $random_string);
  $config->save();
}
